### ISSUE TITLE
Currently transforms non-lazy requires.

### ISSUE THREAD

**Issue by DeadHeadRussell** [doowb/unlazy-loader#25]
With files that have both lazy and non-lazy requires, unlazy-loader transforms them all.  One example is micromatch.

```javascript
var path = require('path');
var fileRe = require('filename-regex');
var utils = require('lazy-cache')(require);

var fn = require;
require = utils;

require('arr-diff', 'diff');

...

require = fn;
```

Currently, the top lines are transformed into the following wrong code:

```javascript
utils.path = require('path');
utils.fileRe = require('filename-regex');
var utils = {};
```

Finding the line number of `require = utils;` and the line number of `require = fn;` then only transforming the requires in between would fix this.

```javascript
var firstLine = source.split('\n').findIndex(function(line) {
  return line == 'require = ' + first.variable + ';';
});

var lastLine = source.split('\n').findIndex(function(line) {
  return line == 'require = fn;';
});
if (lastLine == -1) lastLine = Infinity;

...

results.forEach(function(ele) {
  if (ele.line < firstLine || ele.line > lastLine) return;
  ...
});
```

**Comment by jonschlinkert** [comment]
this doesn't speak to the bug, but fwiw the latest micromatch no longer uses lazy-cache

**Comment by doowb** [comment]
@DeadHeadRussell just merged in @jonschlinkert's changes that should fix this (he even added tests around it).

I'll get this published soon.

**Comment by doowb** [comment]
Published to npm.

**Comment by DeadHeadRussell** [comment]
Awesome, thanks!
